# @package _global_
training_strategy:
  name: group_dro_balanced
  uses_cohort_group_id: true
  supports_warm_start: true
model:
  loss_fn:
    _target_: projects.hypernet_iterative.loss.ClassBalancedGroupDROTaskLoss
    num_groups: ${cohort.num_groups}
    num_classes: ${data.num_classes}
    class_weight: null
    step_size: 0.0001
    loss_ema_momentum: 0.01
    group_key: ${cohort.group_key}
