_target_: projects.hypernet_e2e.module.LitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-2
scheduler: null

net:
  _target_: projects.hypernet_e2e.models.hyperadapt.HyperAdaptResNet
  num_classes: ${data.num_classes}
  rank: 4
  generator_hidden_dim: 128
  backbone:
    _target_: projects.hypernet_e2e.models.resnet.network.ResNetBackbone
    layers: [3, 4, 6, 3]
    block: Bottleneck
  metadata_encoder:
    _target_: projects.hypernet_e2e.models.spatial_hypernet.metadata_encoder.MetadataEncoder
    categorical_cardinalities: ${data.attribute_spec.categorical_cardinalities}
    num_continuous: ${data.attribute_spec.continuous_dim}
    embedding_dim: 4
    hidden_dim: 128
    output_dim: 16

loss_fn:
  _target_: projects.hypernet_e2e.loss.TaskLoss
  class_weight: null

use_attributes: true
backbone_checkpoint_path: null
freeze_backbone: true
attribute_names: ${data.attribute_names}
fairness_attribute_names: ${data.fairness_attribute_names}
compile: false
